#!/bin/bash

echo ------------------------------------------------------------------------
echo "This will checkout '$branch' in all repos"
echo ------------------------------------------------------------------------

baseDir=$(pwd)

echo ------------------------------------------------------------------------
echo ... fetching and updating submodules of TM
echo ------------------------------------------------------------------------

git fetch origin
git submodule update


function checkout {
  echo ------------------------------------------------------------------------
  echo "... checking out $branch inside $1"
  echo ------------------------------------------------------------------------
  cd  $1
  git checkout $branch
  git pull origin $branch:$branch
  cd $baseDir
}

checkout .
checkout code/TM_Flare
checkout code/TM_GraphDB
checkout code/TM_Jade
checkout code/TM_Shared
checkout code/TM_Static
checkout code/TM_Website


./bin/start-servers.sh
