#!/bin/bash

if [[ -z $1 ]]; then
  echo "You must provide the name of the image to build"
  exit 1
fi

# Create temp dir
dir=`mktemp -d -t docker-build-XXXX` && cd $dir

echo '---------------tm-docker-build-----------------------'
echo 'using tmp folder: $dir'
echo '-----------------------------------------------------'

# Clone TM_Docker and checkout branch with target build
git clone git@github.com:TeamMentor/TM_Docker.git
cd TM_Docker
git checkout $1

# Copy key (required to be added into docker container)

if [[ -f ~/.ssh/docker_key ]]; then
  echo 'using ~/.ssh/docker_key'
  cp ~/.ssh/docker_key .
elif [[ -f ~/.ssh/id_rsa ]]; then
  echo "using ~/.ssh.id_rsa which is YOUR main SSH key (make sure you are ok with this)"
  cp ~/.ssh/id_rsa ./docker_key
else
  echo "Error: Could not find an ssh key to use."
  exit 1
fi

# Build container
docker build -t $1 .
