#!/bin/bash

if [[ -z $1 ]]; then
  echo "You must provide the ip of the docker server. You can find it with: do-cli list"
  exit 1
fi
if [[ -z $2 ]]; then
  echo "You must provide the name of the container"
  exit 1
fi

echo "starting container tm-qa-branch script at $1 with design branch $2 and graph branch $3"
ssh root@$1 <<< "cd ~
                 cd TM_Docker
                 git checkout master
                 git pull origin master
                 cd inside-docker
                 ./run-branch tm-qa-branch $2 $3
                 "
